### ISSUE TITLE
How representative are the generated fixture data?

### ISSUE THREAD

**Issue by jgonggrijp** [offen/underscore-benchmark#5]
I see that `generate-fixtures.js` spends some effort to ensure that one third of events is mobile and a quarter has a referrer. Is this based on observations from real-world data?

Otherwise, the randomized values seem to be drawn from a flat distribution. All events are of type `PAGEVIEW`. Are these choices approximately realistic? For example, are other event types rare?

I'm asking because the distribution of values may affect the proportions of time spent in alternative branches of the code, which in turn may affect the running time.

If we end up concluding that the data are not very representative, one possible solution may be to take real data and replace each unique string by another, non-identifying string (using wholesale search/replace) in order to arrive at a single, censored-but-representative dataset.

**Comment by m90** [comment]
> that one third of events is mobile and a quarter has a referrer. Is this based on observations from real-world data?

This is hard/impossible to tell because it will heavily depend on your site. Some sites will have almost exclusively mobile traffic while others have close to none. The number of referrers usually depends on how deep sessions are (i.e. if your site has a single page or mostly bounces, the number of visits with a referrer will be much higher than compared to a complex site with 100s of pages). I picked 1/3 for the mobile share and 1/4 for the referrer values to make sure all code branches run to some extent and also try to find some values that apply to most sites.

> All events are of type PAGEVIEW

This is the only event type currently supported. It is just there so that we could introduce another type at some point in the future.

I would like to prevent having to work against real world data even if pseudonymized in some way as it kind of defeats some principles we follow when building Offen. I also doubt there will be one set of fixtures to rule them all as sites can have vastly different usage patterns.

**Comment by jgonggrijp** [comment]
Works for me!
